### ISSUE TITLE
API Changes (v4)

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/spectator#140]
I think about the following changes: (breaking changes)

```ts
it('should...', () => {
  spectator = createComponent({
    props: {},
    providers: [{ provide: Service, useValue: { } }],
    detectChanges: boolean
  });
});
```

This is a more simple, clean, and scalable approach.

- ~~API changes discuss in this issue~~
- ~~Eagerly initiate a service when using `createService`~~.
- New unit testing suite with coverage thresholds (consider to delete the whole specs files and create a stronger suite from scratch)
- ~~Take a fresh look at the API what to keep, what to add and what to remove/deprecate~~
- new Wiki? Or updating the existing docs
- A new RoutedSpectator (which extends Spectator like SpectatorWithHost) with some additional routing features (let’s keep this one as last and discuss about it in #110)
- https://github.com/NetanelBasal/spectator/pull/95
- ~~Add focus and blur helpers.~~
- ~~Add `keyboard.pressKey` helper~~
- ~~Add support for global queries: `spectator.query(selector, { root: true })`~~
- ~~Add options to override providers inline~~

**Comment by dirkluijk** [comment]
Funny, I had exactly the same idea yesterday when looking at your POC. 😄 

Looks good to me!

**Comment by NetanelBasal** [comment]
It's the right time to bring more ideas if you have.

**Comment by dirkluijk** [comment]
Given:
```typescript
const spectator = createService(FooService);
```

It's a bit unclear that calling `createService()` does not construct the service, unless you invoke `spectator.service` or `spectator.get(FooService)`. In other words, it is lazy which may be unclear.

Normally this is no problem because you should interact with the service first, but not when there is logic in the constructor that you would like to test.

Two possible solutions:
1) Let Spectator perform a `TestBed.get(FooService)` in order to instantiate it eagerly
2) Introduce a ServiceFactory instead, like we already do with components (API changes)

I feel a little bit more comfortable with option 2.

That means the new API would look like this:

```typescript
const createService = createServiceFactory(FooService);

it('should do something', () => {
  const service = createService();
})
```

This would also allow to pass options for services as well, as you proposed in the first comment of this issue:

``typescript
it('should do something', () => {
  const service = createService({
    providers: [{ provide: OtherService, useValue: { } }],
  });
})
```

**Comment by NetanelBasal** [comment]
I would go with option two.

**Comment by lppedd** [comment]
@NetanelBasal a bit off topic, but what's the ETA for release 4?  
I don't want to start writing tests now, if after I'll have to convert them.  
Btw, thanks for the great work ;)

**Comment by NetanelBasal** [comment]
I hope to get it done by the end of the month. Unless @dirkluijk want to help :)

**Comment by dirkluijk** [comment]
Of course. Let’s discuss it what to do and what not.

I was thinking of:
- API changes discusses in this issue (service factories and new factory options)
- New unit testing suite with coverage thresholds
- Take a fresh look at the API what to keep, what to add and what to remove/deprecate
- new Wiki? Or updating the existing docs
- A new RoutedSpectator (which extends Spectator like SpectatorWithHost) with some additional routing features (let’s keep this one as last and discuss about it in https://github.com/NetanelBasal/spectator/issues/110)

**Comment by NetanelBasal** [comment]
Let us revert the changes you made with the query and the types. There are multiple errors. We'll add them to v4. Can you do it?

**Comment by NetanelBasal** [comment]
@dirkluijk tested it, and it works fine. I updated v4 with more things. You can see it in the first comment.

**Comment by NetanelBasal** [comment]
There are still issues with `injection-tokens.jest.ts`

**Comment by dirkluijk** [comment]
Yes I’ll take a look at it.

**Comment by dirkluijk** [comment]
@lppedd feel free to check https://github.com/NetanelBasal/spectator/pull/149 and discuss the proposed changes

**Comment by dirkluijk** [comment]
This issue is being closed, as we are close to finalizing v4.
