### ISSUE TITLE
Errors were found in your package-lock.json

### ISSUE THREAD

**Issue by alexpolgithub** [ngneat/spectator#164]
After installing ng add @netbasal/spectator I get the following error in the terminal.

npm ERR! code ELOCKVERIFY
npm ERR! Errors were found in your package-lock.json, run  npm install  to fix them.
npm ERR!     Invalid: lock file's @netbasal/spectator@3.12.0 does not satisfy @netbasal/spectator@~3.2.1

I am running a brand new Angular 8.1.0 app using the Angular Cli.

**Comment by dirkluijk** [comment]
This is a general issue with NPM unrelated to Spectator.

It seems that the version in your `package-lock.json` is not in sync with your `package.json`. Removing the `package-lock.json` file and running `npm install` again.

Please see https://github.com/npm/npm/issues/16866.

**Comment by alexpolgithub** [comment]
I tried removing the package-lock.json but that did not resolve my issue. This is only happening when I try and install spectator.

**Comment by dirkluijk** [comment]
I will try

**Comment by alexpolgithub** [comment]
> I have successfully reproduced it. I will look into it.
> 
> In the meantime, I think that installing it with `npm install @netbasal/spectator --save-dev` will fix it.
> 
> So:
> 
> ```
> rm package-lock.json
> npm install
> npm install @netbasal/spectator --save-dev
> ```

This solved it for me. Thanks.

**Comment by dirkluijk** [comment]
There are 2 issues here:

* Our schematic adds an old version to `devDependencies`, while the installed version does not match the constraint.
* Angular CLI automatically installs it to `dependencies` too. This issue has been reported here: https://github.com/angular/angular-cli/pull/15410.

If the Angular CLI will support installing devDependencies, we can remove our schematic. Otherwise, we have to remove it from package.json somehow. And fix the incorrect version.

**Comment by dirkluijk** [comment]
Since `4.0.0` the recommended way of installing is using `npm` / `yarn` instead of `ng` due to the lack of `devDependency` support.

Feel free to open a new ticket if you have ideas or questions.

**Comment by manymenrise** [comment]
58:21  error  Unexpected use of file extension "json" for "./package.json"  import/extensions
