### ISSUE TITLE
hostfactory with routing support

### ISSUE THREAD

**Issue by remkoboschker** [ngneat/spectator#207]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I can create a factory for a host and for a routing component.

## Expected behavior
I would like to create a host with routing support in its component.

**Comment by dirkluijk** [comment]
What would be the use case? I mean, routed components are usually rendered dynamically with `<router-outlet />`, and have no inputs/output bindings. So I think it would make less sense to test them in a template.

**Comment by remkoboschker** [comment]
I would not want to use it for routed components, but for components that observe the query parameters or that navigate to a route (perhaps relative to a parent route) or that use route data and so on.

**Comment by dirkluijk** [comment]
I understand. Personally, I think it's good to decouple lower-level components from routing at all. That's why I never needed this myself.

If you really want to, you can do something like this:

```ts
const createHost = createHostFactory({
  component: YourComponent,
  providers: [
    {
       provide: ActivatedRoute,
       useValue: new ActivatedRouteStub({ data: {}, params: {} })
    }
  ];

  it('should react to route changes', () => {
    const spectator = createHost('your template');
    const routeStub = spectator.get<ActivatedRouteStub>(ActivatedRoute);

    routeStub.setParam(name, value);
    routeStub.triggerNavigation();
    spectator.detectChanges();

    // ..
  })
})
```
The `ActivatedRouteStub` can be imported from `@ngneat/spectator`. This is not documented (yet), but should work I think. Find its implementation [here](https://github.com/ngneat/spectator/blob/master/projects/spectator/src/lib/spectator-routing/activated-route-stub.ts).

**Comment by remkoboschker** [comment]
Thank you, that is helpful
