### ISSUE TITLE
Cannot mock child component's DI services

### ISSUE THREAD

**Issue by Lonli-Lokli** [ngneat/spectator#259]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Cannot mock child components services

## Expected behavior

Ability to mock injected services inside child components

## Minimal reproduction of the problem with instructions
https://github.com/Lonli-Lokli/spectator_bug_child

1. Install dependencies and run
yarn test 
All works
Change app.component.spec.ts:
from 
      ChildComponent
      // MockComponent(ChildComponent)
to
      // ChildComponent
      MockComponent(ChildComponent)
and run yarn test

Test failed:
 AppComponent › should create the app

    TypeError: Cannot read property 'value' of undefined

## What is the motivation / use case for changing the behavior?
Ability to mock DI data for child components

## Environment

<pre><code>
Angular version: 8.3

**Comment by benelliott** [comment]
`MockComponent` is part of https://github.com/ike18t/ng-mocks rather than Spectator so you would be better off raising an issue there.

That said, I think you are slightly misusing `MockComponent` - its purpose is to create a mocked version of the component's public APIs. `child.dataService.value.count` is not a public field of the component and it doesn't really make sense for `MockComponent` to mock things to an arbitrary depth.
