### ISSUE TITLE
Feature request: allow overrideComponent option on createComponentFactory

### ISSUE THREAD

**Issue by wimdetroyer** [ngneat/spectator#324]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

There is no option to override the component, and set the changedetectionstrategy back to default

## Expected behavior

Something like this 'vanilla' TestBed configuration but using the spectator library:

```javascript

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ SomeComponent ]
    })
      .overrideComponent(SomeComponent, {
        set: {  changeDetection: ChangeDetectionStrategy.Default  } // detectChanges() works only ones with ChangeDetectionStrategy.onPush
      })
    .compileComponents()
  }));

```

## What is the motivation / use case for changing the behavior?

So I am able to test dumb components which have a ChangeDetectionStrategy.OnPush, which as of now need to be manually overriden to the default or the changedetection only works once:

https://github.com/angular/angular/issues/12313

Apologies if it does exist, however I have looked for a while and could not find anything.

**Comment by NetanelBasal** [comment]
I don't recommend doing this. Your test should reflect the application behavior.

**Comment by NetanelBasal** [comment]
What is your use case? Please provide a stackblitz example.

**Comment by wimdetroyer** [comment]
https://stackblitz.com/edit/angular-ivy-b8hj4u

HelloComponent has a button which is rendered if a checkbox has a value true. I have also supplied a (non-working) test case with the behavior I'd like to test.

**Comment by NetanelBasal** [comment]
Please create it here: https://stackblitz.com/edit/angular-testing-spectator

**Comment by wimdetroyer** [comment]
Ah, perfect! 

https://stackblitz.com/edit/angular-ivy-b8hj4u

Just the test dependencies need to be installed in the StackBlitz.

**Comment by NetanelBasal** [comment]
Please create it here: stackblitz.com/edit/angular-testing-spectator

**Comment by wimdetroyer** [comment]
Please check this fork, test dependencies are now installed:

https://angular-testing-spectator-kaobmu.stackblitz.io

sorry for the hassle ;-)

**Comment by NetanelBasal** [comment]
Your code isn't using Spectator.

**Comment by NetanelBasal** [comment]
Create the Spectator version, please.

**Comment by wimdetroyer** [comment]
How would I go about doing that if I cannot override the component to manually set the change detection strategy in the test? This behaviour **does not exist** in spectator. You asked me to describe my use case, here it is.

**Comment by NetanelBasal** [comment]
No, I asked you to recreate it with Spectator so I can see why it's not working.

**Comment by wimdetroyer** [comment]
overrideComponents() has been commented out of the spec to make the test fail. I see no reason to write it in spectator.

Please also refer to https://github.com/angular/angular/issues/12313 if still unclear.

**Comment by benelliott** [comment]
Your tests work under Spectator if you:

1) disable the initial change detection run in Spectator by changing your `createComponent()` call to `createComponent({detectChanges: false})`
2) use `spectator.detectComponentChanges()` instead of `spectator.detectChanges()`

This method has the advantage of not changing the component's fundamental behaviour in the testing environment in order to get the unit tests to pass.

Here is a working StackBlitz: https://stackblitz.com/edit/angular-testing-spectator-rq1d21

**Comment by NetanelBasal** [comment]
That is what I wanted to show him, but he refused to create it.

**Comment by wimdetroyer** [comment]
Thanks @benelliott ! 🙂 quite a bit more helpful than useless pedantry.

**Comment by panchitoboy** [comment]
Hi,

First of all im really fan of spectator, it was a game changer for the way that we write test in my enterprise. So thank you for this usefull library.

Second i have a question:

Can you explain the difference between use spectator.detectComponentChanges() instead of spectator.detectChanges()? 

I have some trouble to understand when i need to use one or the other.

In my case, i have a template like:

<label *ngIf="formControl.hasError('required')> show some text </label>

When i switch the form control from Valid to invalid ( formControl.setValue(null) ).  Why i need to call detectComponentChanges instead of detectChanges?


Thank you for your time
