### ISSUE TITLE
Test with imported MatSelect fails, because options are not generated

### ISSUE THREAD

**Issue by tommueller** [ngneat/spectator#327]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have a component containing a _mat-select_ (from the Angular Material library). This _mat-select_ contains a list of _mat-options_ generated with an _*ngFor_.
```html
<mat-form-field appearance="fill">
  <mat-label>Toppings</mat-label>
  <mat-select [formControl]="toppings" multiple>
    <mat-option *ngFor="let topping of toppingList" [value]="topping">{{ topping }}</mat-option>
  </mat-select>
</mat-form-field>
```
and the minimal component:
```typescript
export class TestComponent {
  toppings = new FormControl();

  toppingList: string[] = ['Extra cheese', 'Mushroom', 'Onion', 'Pepperoni', 'Sausage', 'Tomato'];
}
```

Now when I write a minimal test (to check that the select includes all options), it almost works:
```typescript
describe('TestComponent', () => {
  let spectator: Spectator<TestComponent>;
  const createComponent = createComponentFactory({
    component: TestComponent
  });

  beforeEach(() => (spectator = createComponent()));

  it('should display all category options', () => {
    expect(spectator.queryAll('mat-option')).toHaveLength(6); // works
    expect(spectator.queryAll(MatOption)).toHaveLength(6); // does NOT work!
  });
});
```
Testing for the component type directly does not work and I get a warning: `WARN: 'Can't bind to 'value' since it isn't a known property of 'mat-option'.'`

When I now add the imports, in order to fix this, the test does not work anymore:
```typescript
  const createComponent = createComponentFactory({
    component: TestComponent,
    imports: [MatSelectModule, ReactiveFormsModule, FormsModule]
  });
```
It gives no error, but the _mat-option_'s are not created, so I get: `ERROR: Expected element to have length 6, but had 0`.

Looking at the _spectator.element_ it seems that nothing is failing, but the _mat-option_'s are indeed not rendered. I have no idea why though. The component also works perfectly fine in the app itself.

## Expected behavior
I would expect the test to still work ;)

## Environment

<pre><code>
Angular 9.1.0
ngneat/spectator 5.12.0
</code></pre>

**Comment by benelliott** [comment]
`MatOption` elements are rendered in an overlay container that lives outside the DOM tree of your component under test. This means the rendered elements won't be returned unless you query from document body.

Your first case probably works because the browser is rendering an unrecognised `mat-select` and `mat-option` tags to the default inline elements. As soon as you are loading in the true `MatSelect` functionality this will cease to work. 

You might want to investigate using Angular Material's [testing harnesses](https://material.angular.io/guide/using-component-harnesses) which will hide the implementation details of the Material components under more user-friendly APIs.

**Comment by tommueller** [comment]
Thanks @benelliott for the explanation and the hint to the testing harness.
